require("prismjs/plugins/command-line/prism-command-line.css")
require("prismjs/plugins/copy-to-clipboard/prism-copy-to-clipboard.js")
require("prismjs/plugins/show-language/prism-show-language.js")
require("prismjs/themes/prism-okaidia.css")
// require("prismjs/themes/prism-coy.css")
// require("./src/styles/prism-atom-dark.css")
